// The Zod schemas against frames recorded from the real server (SD26, PD19).
// The fixture is regenerated by `uv run python -m tests.api.ws_fixture
// --write`, and the gate fails if it no longer matches the server -- so a
// schema passing here matches what the server sends today.
import { describe, expect, it } from 'vitest'
import fixture from './__fixtures__/ws-messages.json'
import { ClientMessage, ServerMessage, SERVER_MESSAGE_TYPES } from './schemas'

const frames = Object.entries(fixture as Record<string, unknown>)

describe('ServerMessage', () => {
  it.each(frames)('parses the recorded %s frame', (_name, frame) => {
    const parsed = ServerMessage.safeParse(frame)
    expect(parsed.error?.issues ?? []).toEqual([])
  })

  it('has a recorded frame for every server message type', () => {
    const recorded = new Set(frames.map(([, frame]) => (frame as { type: string }).type))
    expect([...SERVER_MESSAGE_TYPES].sort()).toEqual([...recorded].sort())
  })

  it('records both ends of a market event', () => {
    expect(fixture.market_event_start.data.op).toBe('start')
    expect(fixture.market_event_end.data.op).toBe('end')
  })

  it('rejects a field the server does not send', () => {
    const frame = { ...fixture.pong, data: { ...fixture.pong.data, extra: 1 } }
    expect(ServerMessage.safeParse(frame).success).toBe(false)
  })

  it('rejects data of another type', () => {
    expect(ServerMessage.safeParse({ ...fixture.pong, type: 'tick' }).success).toBe(false)
  })

  it('rejects a float price', () => {
    const tick = structuredClone(fixture.tick) as { data: { drinks: Record<string, unknown> } }
    const [id] = Object.keys(tick.data.drinks)
    tick.data.drinks[id] = { ...(tick.data.drinks[id] as object), price_cents: 2.5 }
    expect(ServerMessage.safeParse(tick).success).toBe(false)
  })
})

describe('ClientMessage', () => {
  it.each([
    [{ type: 'hello', boot_id: 'b', last_seq: 3 }],
    [{ type: 'ping' }],
    [{ type: 'resync_request' }],
  ])('accepts %o', (message) => {
    expect(ClientMessage.safeParse(message).success).toBe(true)
  })

  it.each([[{ type: 'order' }], [{ type: 'ping', x: 1 }], [{ type: 'hello', boot_id: 'b' }]])(
    'rejects %o',
    (message) => {
      expect(ClientMessage.safeParse(message).success).toBe(false)
    },
  )
})
