#!/usr/bin/env bash
# BorrelBeurs -- the gate (AC4, plan T9).
#
# Every check this repository has, in one place, fastest first (way-of-working
# 7.3:1179), stopping at the first failure. CI runs this script verbatim (T11)
# rather than restating its steps in YAML, so "green locally" and "green in CI"
# are the same claim.
#
# Needs a running Postgres for the last step: locally the compose `db` that
# scripts/setup.sh starts, in CI a service container. The environment comes
# from .env.local when it exists (local), and from the process otherwise (CI).
#
# Git Bash only (plan R2).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

require() {
  local tool="$1" hint="$2"
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "scripts/check.sh: '${tool}' is required but not installed. ${hint}" >&2
    exit 1
  fi
}

require uv "Install uv: https://docs.astral.sh/uv/getting-started/installation/"
require pnpm "Install pnpm: https://pnpm.io/installation (or 'corepack enable pnpm')"

# app/core/config.py reads the process environment only, so .env.local has to
# be exported for the integration step to see it -- same as scripts/setup.sh.
# Absent in CI, where the workflow sets the variables itself.
if [ -f .env.local ]; then
  set -a
  # shellcheck disable=SC1091  # generated by scripts/setup.sh, gitignored
  . ./.env.local
  set +a
fi

TOTAL=9
STEP=0

step() {
  local name="$1"
  shift
  STEP=$((STEP + 1))
  printf '\n==> [%d/%d] %s\n' "$STEP" "$TOTAL" "$name"
  if ! "$@"; then
    printf '\nscripts/check.sh: FAILED at step %d/%d (%s)\n' "$STEP" "$TOTAL" "$name" >&2
    exit 1
  fi
}

# Directories allowed to hold no tests yet. pytest exits 5 on "no tests
# collected"; that is green only for a directory named here, never globally,
# so a collection error (exit 2) or a directory whose tests all vanished is
# still red (plan R10). tests/engine fills up in Phase 1 -- delete it from this
# list then.
ALLOW_EMPTY=" tests/engine "

pytest_each() {
  local dir status
  for dir in "$@"; do
    status=0
    uv run pytest "$dir" || status=$?
    if [ "$status" -eq 5 ] && [[ "$ALLOW_EMPTY" == *" $dir "* ]]; then
      echo "scripts/check.sh: no tests in ${dir} yet -- allowed"
    elif [ "$status" -ne 0 ]; then
      return "$status"
    fi
  done
}

step "ruff format --check" uv run ruff format --check .
step "ruff check" uv run ruff check .
step "web format:check" pnpm --dir web format:check
step "web lint" pnpm --dir web lint
step "mypy app db tests" uv run mypy app db tests
step "web tsc -b" pnpm --dir web exec tsc -b
step "pytest tests/unit tests/meta tests/engine" pytest_each tests/unit tests/meta tests/engine
step "web test" pnpm --dir web test --run
step "pytest tests/integration" pytest_each tests/integration

printf '\nscripts/check.sh: all %d steps passed\n' "$TOTAL"
